[package]
name = "wasi-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow = "1"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.22.0", features = [ "rt-multi-thread", "macros" ] }
wasi-cap-std-sync = { version = "11.0.0" }
wasi-common = { version = "11.0.0" }
wasmtime = { version = "11.0.0", features = ['component-model', 'default']}
wasmtime-wasi = { version = "11.0.0" }
wasmtime-wasi-http = { version = "11.0.0" }

[build-dependencies]
js-component-bindgen = { git = "https://github.com/eduardomourar/jco", branch = "update-wit-wasmtime-v10" }
wit-component = "0.11.0"
