[package]
name = "wasi-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow = "1"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }

[build-dependencies]
js-component-bindgen = { version = "0.11", git = "https://github.com/bytecodealliance/jco" }
