[package]
name = "wasi-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow = "1"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
wasmtime = { version = "14.0.0", git = "https://github.com/bytecodealliance/wasmtime", features = [
    'component-model',
] }
wasmtime-wasi = { version = "14.0.0", git = "https://github.com/bytecodealliance/wasmtime" }
wasmtime-wasi-http = { version = "14.0.0", git = "https://github.com/bytecodealliance/wasmtime" }

[build-dependencies]
js-component-bindgen = { version = "0.11", git = "https://github.com/bytecodealliance/jco" }
