[workspace]
members = [
    "packages/aws-cli",
    "packages/credentials-adapter",
    "packages/simple-http-proxy",
    "packages/wasi-engine",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = [
    "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
edition = "2024"

[profile.release]
lto = true
panic = "abort"

[profile.release.package.aws-cli]
codegen-units = 1
opt-level = "s"
strip = true

[profile.release.package.simple-http-proxy]
codegen-units = 1
opt-level = "s"
strip = "debuginfo"

[profile.release.package.credentials-adapter]
codegen-units = 1
opt-level = "s"
strip = true

[workspace.dependencies]
anyhow = { version = "1.0" }
bytes = { version = "1.5" }
tokio = { version = "1.52", default-features = false }
wasmtime = { version = "45" }
wasmtime-wasi = { version = "45" }
wasmtime-wasi-http = { version = "45" }

[workspace.metadata.bin]
cargo-component = { version = "^0.21", locked = true }
wasmtime-cli = { version = "^45", bins = [
    "wasmtime",
], locked = true, features = [
    "component-model",
] }
wkg = { version = "^0.15", locked = true }
