[workspace]
members = [
    "packages/aws-cli",
    "packages/providers-adapter",
    "packages/simple-http-proxy",
    "packages/wasi-engine",
]
exclude = ["tools/generate-ops"]
resolver = "3"

[workspace.package]
version = "0.0.1"
authors = [
    "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0" }
bytes = { version = "1.5" }
tokio = { version = "1.52", default-features = false }
wasmtime = { version = "48" }
wasmtime-wasi = { version = "48" }
wasmtime-wasi-http = { version = "48" }

[workspace.metadata.bin]
cargo-component = { version = "^0.21", locked = true }
wasmtime-cli = { version = "^48", bins = [
    "wasmtime",
], locked = true, features = [
    "component-model",
] }
wkg = { version = "^0.15", locked = true }
