use anyhow::{Error, Result};
use aws_sdk_athena::Client;
use clap::Args;

/// Arguments for `athena list-work-groups`.
#[derive(Debug, Clone, Args)]
pub struct ListWorkGroups {
    /// The maximum number of workgroups to return in this request.
    #[arg(long)]
    pub max_results: Option<i32>,
    /// A token generated by the Athena service that specifies where to continue
    #[arg(long)]
    pub next_token: Option<String>,
}

/// Execute `athena list-work-groups`.
pub(crate) async fn list_work_groups(
    client: &Client,
    args: ListWorkGroups,
) -> Result<serde_json::Value, Error> {
    tracing::debug!("Preparing `ListWorkGroups` operation to AWS SDK");
    let mut req = client.list_work_groups();
    if let Some(val) = args.max_results {
        req = req.max_results(val);
    }
    if let Some(ref val) = args.next_token {
        req = req.next_token(val);
    }
    let resp = req.send().await?;
    Ok(serde_json::json!({
    "nextToken": resp.next_token(),
    "workGroups": resp.work_groups().iter().map(|v| serde_json::json!({
    "creationTime": v.creation_time().map(|t| t.to_string()),
    "description": v.description(),
    "identityCenterApplicationArn": v.identity_center_application_arn(),
    "name": v.name(),
    "state": v.state().map(|e| e.as_str()),
    })).collect::<Vec<_>>(),
    }))
}
