[alias]
component = ["bin", "cargo-component"]

[target.wasm32-wasip2]
runner = [
    "cargo",
    "bin",
    "wasmtime",
    "--dir",
    "/tmp",
    "-C",
    "cache=no",
    "-D",
    "debug-info",
    "-S",
    "cli",
    "-S",
    "http",
]
