[package]
name = "wasi-http-preview2-component"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["lib"]

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"wasi:cli" = { path = "wit/deps/cli" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:filesystem" = { path = "wit/deps/filesystem" }
"wasi:http" = { path = "wit/deps/http" }
"wasi:io" = { path = "wit/deps/io" }
"wasi:logging" = { path = "wit/deps/logging" }
"wasi:poll" = { path = "wit/deps/poll" }
"wasi:random" = { path = "wit/deps/random" }
"wasi:sockets" = { path = "wit/deps/sockets" }

[package.metadata.component.registries]
ba-preview-registry = "https://preview-registry.bytecodealliance.org"

[dependencies]
cargo-component-bindings = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
