name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_DIR: "${{ github.workspace }}/target"
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Cache cargo
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${CARGO_TARGET_DIR}/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Cache cargo run bin
        uses: actions/cache@v5
        with:
          path: |
            .bin/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}

      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@v1.20.1
      - name: Install cargo-run-bin
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo binstall cargo-run-bin -y --locked
          cargo bin --install
      - name: Build
        run: |
          CARGO_PROFILE_DEV_LTO=thin cargo component build --target wasm32-wasip2 --workspace --exclude wasi-engine
          cargo build -p wasi-engine
      - name: Check formatting
        run: cargo fmt --all
      - name: Run clippy action to produce annotations
        uses: actions-rs-plus/clippy-check@v2
        with:
          args: --all-targets --all-features --no-deps
          token: ${{ secrets.GITHUB_TOKEN }}
          use-cross: false

      - name: Test WebAssembly components
        run: |
          CARGO_PROFILE_DEV_LTO=thin cargo component check --target wasm32-wasip2 --workspace --exclude wasi-engine
          cargo check -p wasi-engine
          export RUST_TEST_NOCAPTURE=1
          cargo test -p aws-cli --lib
          cargo test -p simple-http-proxy --target wasm32-wasip2
          export RUST_LOG="trace,cranelift_codegen=off,cranelift_wasm=off,wasmtime_cranelift=off"
          cargo test -p aws-cli --test integration_test -- --test-threads=2

  pr-success:
    needs:
      - build
    # if pr-success is skipped, GH branch protection will not consider it a failure, we need to check the result of each dependency ourself
    # see: https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
    if: always()
    steps:
      - if: needs.build.result == 'failure'
        run: echo "build job failed, setting the failure() bit" && exit 1
      - if: success()
        run: echo "all dependencies succeeded"
    runs-on: ubuntu-latest
