name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Cache cargo run bin
        uses: actions/cache@v3
        with:
          path: |
            .bin/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}

      - name: Install cargo binstall
        if: steps.cache.outputs.cache-hit != 'true'
        uses: cargo-bins/cargo-binstall@v1.3.1
      - name: Install cargo-run-bin
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install cargo-run-bin --locked --git https://github.com/dustinblackman/cargo-run-bin --rev 7151499b4b47861f84c63b958af8cd36aa8648a9
      - name: Build WebAssembly components
        run: cargo component build --workspace --exclude wasi-engine
      - name: Build
        run: |
          cargo build
          cargo bin --install
      - name: Check formatting
        run: cargo fmt --all
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets --all-features --no-deps
          token: ${{ secrets.GITHUB_TOKEN }}
          use-cross: false

      - name: Test WebAssembly components
        run: |
          cargo component check --workspace --exclude wasi-engine
          export RUST_LOG="trace,cranelift_codegen=off,cranelift_wasm=off,wasmtime_cranelift=off"
          export RUST_TEST_NOCAPTURE=1
          RUST_BACKTRACE=1 WASMTIME_BACKTRACE_DETAILS=1 cargo component test --workspace --exclude wasi-engine

  pr-success:
    needs:
      - build
    # if pr-success is skipped, GH branch protection will not consider it a failure, we need to check the result of each dependency ourself
    # see: https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
    if: always()
    steps:
      - if: needs.build.result == 'failure'
        run: echo "build job failed, setting the failure() bit" && exit 1
      - if: success()
        run: echo "all dependencies succeeded"
    runs-on: ubuntu-latest
