name: deploy

on:
  workflow_dispatch: {}
  push:
    branches: [main]

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: "www/package.json"

      - name: Install Dependencies
        working-directory: www
        run: npm ci

      - name: Prepare Web Page
        working-directory: www
        run: |
          npm run build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload Web Page Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: www/dist/
      - name: Deploy Web Page
        uses: actions/deploy-pages@v2
